# Generated by Django 2.2.5 on 2019-10-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='incorrect_attempts',
        ),
    ]
