# Generated by Django 2.2.5 on 2019-09-24 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='looking for executor', max_length=30),
        ),
    ]
