# Generated by Django 2.2.5 on 2019-10-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_tasks_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='invited_to',
        ),
        migrations.AddField(
            model_name='offers',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='categories.Tasks'),
        ),
    ]
