# Generated by Django 2.2.5 on 2019-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20190924_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Looking for executor', 'looking_for_executor'), ('In process', 'in_process'), ('Done', 'done')], default='looking for executor', max_length=30),
        ),
    ]
