# Generated by Django 2.2.5 on 2019-10-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_comments_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='for_whom',
            field=models.PositiveIntegerField(),
        ),
    ]
