# Generated by Django 2.2.5 on 2019-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190924_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
