# Generated by Django 2.2.5 on 2019-09-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20190924_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='name',
        ),
        migrations.AddField(
            model_name='categories',
            name='picture',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
