# Generated by Django 2.2.5 on 2019-09-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20190926_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
