# Generated by Django 2.2.5 on 2019-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20191006_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='from_whom',
            field=models.CharField(max_length=50),
        ),
    ]
