# Generated by Django 2.2.5 on 2019-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20190926_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
