# Generated by Django 2.2.5 on 2019-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20191006_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='from_whom',
            field=models.PositiveIntegerField(),
        ),
    ]
