# Generated by Django 2.2.5 on 2019-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20191006_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
