# Generated by Django 2.2.5 on 2019-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_comments_is_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
