# Generated by Django 2.2.5 on 2019-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20191017_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_positive',
            field=models.BooleanField(),
        ),
    ]
